// generated by stringer -type tag tag.go; DO NOT EDIT

package timesheet

import "fmt"

const _tag_name = "UnknownCommentTextYearMonth"

var _tag_index = [...]uint8{0, 7, 14, 18, 22, 27}

func (i tag) String() string {
	if i < 0 || i >= tag(len(_tag_index)-1) {
		return fmt.Sprintf("tag(%d)", i)
	}
	return _tag_name[_tag_index[i]:_tag_index[i+1]]
}
